In [7]:
from pymove import stay_point_detection

In [8]:
import pandas as pd
from pymove import MoveDataFrame

In [12]:
df = pd.read_csv('examples/geolife_sample.csv', parse_dates=['datetime'])
df.head()

         lat         lon            datetime  id
0  39.984094  116.319236 2008-10-23 05:53:05   1
1  39.984198  116.319322 2008-10-23 05:53:06   1
2  39.984224  116.319402 2008-10-23 05:53:11   1
3  39.984211  116.319389 2008-10-23 05:53:16   1
4  39.984217  116.319422 2008-10-23 05:53:21   1

In [13]:
df_move = MoveDataFrame(df, latitude="lat", longitude="lon", datetime="datetime")

In [5]:
stay_point_detection.create_update_move_and_stop_by_radius(df_move)

Creating or updating features MOVE and STOPS...


Creating or updating distance features in meters...

...Sorting by id and datetime to increase performance

...Set id as index to increase attribution performance

(217653/217653) 100% in 00:00:00.090 - estimated end in 00:00:00.000
...Reset index

..Total Time: 0.09773993492126465

....There are 14691 stops to this parameters

In [6]:
df_move

,id,lat,lon,datetime,dist_to_prev,dist_to_next,dist_prev_to_next,situation
0,1,39.984094,116.319236,2008-10-23 05:53:05,NaN,13.690153,NaN,nan
1,1,39.984198,116.319322,2008-10-23 05:53:06,13.690153,7.403788,20.223428,move
2,1,39.984224,116.319402,2008-10-23 05:53:11,7.403788,1.821083,5.888579,move
3,1,39.984211,116.319389,2008-10-23 05:53:16,1.821083,2.889671,1.873356,move
4,1,39.984217,116.319422,2008-10-23 05:53:21,2.889671,66.555997,68.727260,move
5,1,39.984710,116.319865,2008-10-23 05:53:23,66.555997,6.162987,60.622358,move
6,1,39.984674,116.319810,2008-10-23 05:53:28,6.162987,6.488225,12.450907,move
7,1,39.984623,116.319773,2008-10-23 05:53:33,6.488225,3.971848,10.066577,move
8,1,39.984606,116.319732,2008-10-23 05:53:38,3.971848,5.681172,8.477733,move
9,1,39.984555,116.319728,2008-10-23 05:53:43,5.681172,4.395924,4.353285,move
10,1,39.984579,116.319769,2008-10-23 05:53:48,4.395924,0.000000,4.395924,move
11,1,39.984579,116.319769,2008-10-23 05:53:51,0.000000,0.338804,0.338804,stop
12,1,39.984577,116.319766,2008-10-23 05:53:53,0.338804,6.087463,5.749039,move
13,1,39.984611,116.319822,2008-10-23 05:53:58,6.087463,40.672170,45.862647,move
14,1,39.984959,116.319969,2008-10-23 05:54:03,40.672170,11.324767,51.291054,move
15,1,39.985036,116.320056,2008-10-23 05:54:04,11.324767,32.842422,24.923216,move
16,1,39.984741,116.320037,2008-10-23 05:54:05,32.842422,15.199759,46.577363,move
17,1,39.984620,116.320120,2008-10-23 05:54:07,15.199759,14.428901,29.249419,move
18,1,39.984530,116.320242,2008-10-23 05:54:11,14.428901,7.967597,21.869475,move
19,1,39.984508,116.320331,2008-10-23 05:54:16,7.967597,10.072480,17.142789,move
20,1,39.984537,116.320443,2008-10-23 05:54:21,10.072480,11.111606,20.750102,move
21,1,39.984529,116.320573,2008-10-23 05:54:26,11.111606,11.700748,21.919059,move
22,1,39.984466,116.320683,2008-10-23 05:54:30,11.700748,10.280271,21.979640,move
23,1,39.984409,116.320778,2008-10-23 05:54:34,10.280271,10.221096,19.415958,move
24,1,39.984320,116.320808,2008-10-23 05:54:38,10.221096,7.715212,17.930217,move
25,1,39.984252,116.320826,2008-10-23 05:54:43,7.715212,2.185253,9.620048,move
26,1,39.984238,116.320844,2008-10-23 05:54:48,2.185253,1.016413,3.199618,move
27,1,39.984232,116.320853,2008-10-23 05:54:53,1.016413,2.126326,2.387136,move
28,1,39.984246,116.320870,2008-10-23 05:54:58,2.126326,2.281896,4.258306,move
29,1,39.984266,116.320876,2008-10-23 05:55:03,2.281896,4.400695,6.122292,move
...,...,...,...,...,...,...,...,...
217623,5,40.001137,116.326452,2009-03-19 05:44:02,5.587506,6.845641,12.292447,move
217624,5,40.001103,116.326519,2009-03-19 05:44:07,6.845641,7.920028,13.259258,move
217625,5,40.001126,116.326607,2009-03-19 05:44:12,7.920028,6.423851,12.676896,move
217626,5,40.001091,116.326667,2009-03-19 05:44:17,6.423851,6.128231,12.393729,move
217627,5,40.001073,116.326735,2009-03-19 05:44:22,6.128231,7.325387,13.269371,move
217628,5,40.001073,116.326821,2009-03-19 05:44:27,7.325387,7.197242,14.501320,move
217629,5,40.001080,116.326905,2009-03-19 05:44:32,7.197242,6.182078,13.287911,move
217630,5,40.001073,116.326977,2009-03-19 05:44:37,6.182078,5.207795,11.383505,move
217631,5,40.001064,116.327037,2009-03-19 05:44:42,5.207795,4.051760,8.497267,move
217632,5,40.001033,116.327062,2009-03-19 05:44:47,4.051760,1.400154,4.889527,move
217633,5,40.001022,116.327054,2009-03-19 05:44:52,1.400154,0.000000,1.400154,move
217634,5,40.001022,116.327054,2009-03-19 05:44:55,0.000000,0.358402,0.358402,stop
217635,5,40.001023,116.327058,2009-03-19 05:44:57,0.358402,1.193315,1.485970,move
217636,5,40.001019,116.327071,2009-03-19 05:45:02,1.193315,28.946922,29.466473,move
217637,5,40.000759,116.327088,2009-03-19 05:45:07,28.946922,18.331999,47.148573,move
217638,5,40.000595,116.327066,2009-03-19 05:45:12,18.331999,9.926875,27.905967,move
217639,5,40.000514,116.327017,2009-03-19 05:45:17,9.926875,6.340400,15.858546,move
217640,5,40.000457,116.327019,2009-03-19 05:45:22,6.340400,10.877438,16.896917,move
217641,5,40.000368,116.327072,2009-03-19 05:45:27,10.877438,8.887992,19.705708,move
217642,5,40.000291,116.327100,2009-03-19 05:45:32,8.887992,11.406650,20.062949,move
217643,5,40.000205,116.327173,2009-03-19 05:45:37,11.406650,8.563704,19.107146,move
217644,5,40.000128,116.327171,2009-03-19 05:45:42,8.563704,6.595796,15.131144,move
217645,5,40.000069,116.327179,2009-03-19 05:45:47,6.595796,8.293470,14.701736,move
217646,5,40.000001,116.327219,2009-03-19 05:45:52,8.293470,9.143413,16.900498,move
217647,5,39.999919,116.327211,2009-03-19 05:45:57,9.143413,7.198855,13.148858,move
217648,5,39.999896,116.327290,2009-03-19 05:46:02,7.198855,5.291709,12.214590,move
217649,5,39.999899,116.327352,2009-03-19 05:46:07,5.291709,6.241949,10.400206,move
217650,5,39.999945,116.327394,2009-03-19 05:46:12,6.241949,8.462920,14.628012,move
217651,5,40.000015,116.327433,2009-03-19 05:46:17,8.462920,4.713399,6.713456,move
217652,5,39.999978,116.327460,2009-03-19 05:46:37,4.713399,NaN,NaN,move

In [14]:
stay_point_detection.create_or_update_move_stop_by_dist_time(df_move)

Split trajectories by max distance between adjacent points: 30

Creating or updating distance features in meters...

...Sorting by id and datetime to increase performance

...Set id as index to increase attribution performance

(217653/217653) 100% in 00:00:00.089 - estimated end in 00:00:00.000
...Reset index

..Total Time: 0.09673905372619629
...setting id as index
(217653/217653) 100% in 00:00:00.094 - estimated end in 00:00:00.000
... Reseting index

Total Time: 0.10 seconds
------------------------------------------


Creating or updating distance, time and speed features in meters by seconds

...Sorting by segment_stop and datetime to increase performance

...Set segment_stop as index to a higher peformance

(5/217653) 0% in 00:00:00.185 - estimated end in 02:14:13.658
(43973/217653) 20% in 00:00:00.235 - estimated end in 00:00:00.931
(88533/217653) 40% in 00:00:00.286 - estimated end in 00:00:00.418
(130666/217653) 60% in 00:00:00.363 - estimated end in 00:00:00.242
(174240/217653) 80% in 00:00:00.630 - estimated end in 00:00:00.157
...Reset index...

..Total Time: 0.784
Create or update stop as True or False
...Creating stop features as True or False using 900 to time in seconds
True     152603
False     65050
Name: stop, dtype: int64

Total Time: 1.24 seconds
-----------------------------------------------------

In [15]:
df_move

,segment_stop,id,lat,lon,datetime,dist_to_prev,dist_to_next,dist_prev_to_next,time_to_prev,speed_to_prev,stop
0,1,1,39.984094,116.319236,2008-10-23 05:53:05,NaN,13.690153,NaN,NaN,NaN,False
1,1,1,39.984198,116.319322,2008-10-23 05:53:06,13.690153,7.403788,20.223428,1.0,13.690153,False
2,1,1,39.984224,116.319402,2008-10-23 05:53:11,7.403788,1.821083,5.888579,5.0,1.480758,False
3,1,1,39.984211,116.319389,2008-10-23 05:53:16,1.821083,2.889671,1.873356,5.0,0.364217,False
4,1,1,39.984217,116.319422,2008-10-23 05:53:21,2.889671,66.555997,68.727260,5.0,0.577934,False
5,2,1,39.984710,116.319865,2008-10-23 05:53:23,NaN,6.162987,60.622358,NaN,NaN,False
6,2,1,39.984674,116.319810,2008-10-23 05:53:28,6.162987,6.488225,12.450907,5.0,1.232597,False
7,2,1,39.984623,116.319773,2008-10-23 05:53:33,6.488225,3.971848,10.066577,5.0,1.297645,False
8,2,1,39.984606,116.319732,2008-10-23 05:53:38,3.971848,5.681172,8.477733,5.0,0.794370,False
9,2,1,39.984555,116.319728,2008-10-23 05:53:43,5.681172,4.395924,4.353285,5.0,1.136234,False
10,2,1,39.984579,116.319769,2008-10-23 05:53:48,4.395924,0.000000,4.395924,5.0,0.879185,False
11,2,1,39.984579,116.319769,2008-10-23 05:53:51,0.000000,0.338804,0.338804,3.0,0.000000,False
12,2,1,39.984577,116.319766,2008-10-23 05:53:53,0.338804,6.087463,5.749039,2.0,0.169402,False
13,2,1,39.984611,116.319822,2008-10-23 05:53:58,6.087463,40.672170,45.862647,5.0,1.217493,False
14,3,1,39.984959,116.319969,2008-10-23 05:54:03,NaN,11.324767,51.291054,NaN,NaN,False
15,3,1,39.985036,116.320056,2008-10-23 05:54:04,11.324767,32.842422,24.923216,1.0,11.324767,False
16,4,1,39.984741,116.320037,2008-10-23 05:54:05,NaN,15.199759,46.577363,NaN,NaN,False
17,4,1,39.984620,116.320120,2008-10-23 05:54:07,15.199759,14.428901,29.249419,2.0,7.599879,False
18,4,1,39.984530,116.320242,2008-10-23 05:54:11,14.428901,7.967597,21.869475,4.0,3.607225,False
19,4,1,39.984508,116.320331,2008-10-23 05:54:16,7.967597,10.072480,17.142789,5.0,1.593519,False
20,4,1,39.984537,116.320443,2008-10-23 05:54:21,10.072480,11.111606,20.750102,5.0,2.014496,False
21,4,1,39.984529,116.320573,2008-10-23 05:54:26,11.111606,11.700748,21.919059,5.0,2.222321,False
22,4,1,39.984466,116.320683,2008-10-23 05:54:30,11.700748,10.280271,21.979640,4.0,2.925187,False
23,4,1,39.984409,116.320778,2008-10-23 05:54:34,10.280271,10.221096,19.415958,4.0,2.570068,False
24,4,1,39.984320,116.320808,2008-10-23 05:54:38,10.221096,7.715212,17.930217,4.0,2.555274,False
25,4,1,39.984252,116.320826,2008-10-23 05:54:43,7.715212,2.185253,9.620048,5.0,1.543042,False
26,4,1,39.984238,116.320844,2008-10-23 05:54:48,2.185253,1.016413,3.199618,5.0,0.437051,False
27,4,1,39.984232,116.320853,2008-10-23 05:54:53,1.016413,2.126326,2.387136,5.0,0.203283,False
28,4,1,39.984246,116.320870,2008-10-23 05:54:58,2.126326,2.281896,4.258306,5.0,0.425265,False
29,4,1,39.984266,116.320876,2008-10-23 05:55:03,2.281896,4.400695,6.122292,5.0,0.456379,False
...,...,...,...,...,...,...,...,...,...,...,...
217623,4809,5,40.001137,116.326452,2009-03-19 05:44:02,5.587506,6.845641,12.292447,5.0,1.117501,False
217624,4809,5,40.001103,116.326519,2009-03-19 05:44:07,6.845641,7.920028,13.259258,5.0,1.369128,False
217625,4809,5,40.001126,116.326607,2009-03-19 05:44:12,7.920028,6.423851,12.676896,5.0,1.584006,False
217626,4809,5,40.001091,116.326667,2009-03-19 05:44:17,6.423851,6.128231,12.393729,5.0,1.284770,False
217627,4809,5,40.001073,116.326735,2009-03-19 05:44:22,6.128231,7.325387,13.269371,5.0,1.225646,False
217628,4809,5,40.001073,116.326821,2009-03-19 05:44:27,7.325387,7.197242,14.501320,5.0,1.465077,False
217629,4809,5,40.001080,116.326905,2009-03-19 05:44:32,7.197242,6.182078,13.287911,5.0,1.439448,False
217630,4809,5,40.001073,116.326977,2009-03-19 05:44:37,6.182078,5.207795,11.383505,5.0,1.236416,False
217631,4809,5,40.001064,116.327037,2009-03-19 05:44:42,5.207795,4.051760,8.497267,5.0,1.041559,False
217632,4809,5,40.001033,116.327062,2009-03-19 05:44:47,4.051760,1.400154,4.889527,5.0,0.810352,False
217633,4809,5,40.001022,116.327054,2009-03-19 05:44:52,1.400154,0.000000,1.400154,5.0,0.280031,False
217634,4809,5,40.001022,116.327054,2009-03-19 05:44:55,0.000000,0.358402,0.358402,3.0,0.000000,False
217635,4809,5,40.001023,116.327058,2009-03-19 05:44:57,0.358402,1.193315,1.485970,2.0,0.179201,False
217636,4809,5,40.001019,116.327071,2009-03-19 05:45:02,1.193315,28.946922,29.466473,5.0,0.238663,False
217637,4809,5,40.000759,116.327088,2009-03-19 05:45:07,28.946922,18.331999,47.148573,5.0,5.789384,False
217638,4809,5,40.000595,116.327066,2009-03-19 05:45:12,18.331999,9.926875,27.905967,5.0,3.666400,False
217639,4809,5,40.000514,116.327017,2009-03-19 05:45:17,9.926875,6.340400,15.858546,5.0,1.985375,False
217640,4809,5,40.000457,116.327019,2009-03-19 05:45:22,6.340400,10.877438,16.896917,5.0,1.268080,False
217641,4809,5,40.000368,116.327072,2009-03-19 05:45:27,10.877438,8.887992,19.705708,5.0,2.175488,False
217642,4809,5,40.000291,116.327100,2009-03-19 05:45:32,8.887992,11.406650,20.062949,5.0,1.777598,False
217643,4809,5,40.000205,116.327173,2009-03-19 05:45:37,11.406650,8.563704,19.107146,5.0,2.281330,False
217644,4809,5,40.000128,116.327171,2009-03-19 05:45:42,8.563704,6.595796,15.131144,5.0,1.712741,False
217645,4809,5,40.000069,116.327179,2009-03-19 05:45:47,6.595796,8.293470,14.701736,5.0,1.319159,False
217646,4809,5,40.000001,116.327219,2009-03-19 05:45:52,8.293470,9.143413,16.900498,5.0,1.658694,False
217647,4809,5,39.999919,116.327211,2009-03-19 05:45:57,9.143413,7.198855,13.148858,5.0,1.828683,False
217648,4809,5,39.999896,116.327290,2009-03-19 05:46:02,7.198855,5.291709,12.214590,5.0,1.439771,False
217649,4809,5,39.999899,116.327352,2009-03-19 05:46:07,5.291709,6.241949,10.400206,5.0,1.058342,False
217650,4809,5,39.999945,116.327394,2009-03-19 05:46:12,6.241949,8.462920,14.628012,5.0,1.248390,False
217651,4809,5,40.000015,116.327433,2009-03-19 05:46:17,8.462920,4.713399,6.713456,5.0,1.692584,False
217652,4809,5,39.999978,116.327460,2009-03-19 05:46:37,4.713399,NaN,NaN,20.0,0.235670,False

In [16]:
df_move.stop.unique()

array([False,  True])

In [17]:
df_move['stop'].value_counts()

True     152603
False     65050
Name: stop, dtype: int64